services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.2
    #image: crafty-controller/crafty-4:arm64
    restart: always
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "19132:19132/udp"          # Bedrock
      - "25500-25600:25500-25600"  # Minecraft servers port range
    volumes:
      - ${BASE_DATA_PATH:-./data}/minecraft/backups:/crafty/backups
      - ${BASE_DATA_PATH:-./data}/minecraft/logs:/crafty/logs
      - ${BASE_DATA_PATH:-./data}/minecraft/servers:/crafty/servers
      - ${BASE_DATA_PATH:-./data}/minecraft/config:/crafty/app/config
      - ${BASE_DATA_PATH:-./data}/minecraft/import:/crafty/import
    networks:
      - crafty_internal_net

networks:
  crafty_internal_net:
    external: true